name: NoMilkClearing
version: '${project.version}'
main: net.rainpaw10.nomilkclearing.NoMilkClearing
description: A plugin that removes the ability for milk to clear specific effects.
authors: [
  rainpaw10
]
api-version: '1.20'
